### ISSUE TITLE
feat: Suggestion voter lists

### ISSUE THREAD

**Issue by alaninnovates** [suggestionsbot/suggestions-bot-v3#15]
In the original implementation of suggestions with reactions, we were able to see a list of everyone who had reacted with a ✅ or a ❌ to a suggestion through the Discord feature of viewing who reacted to a emoji. However, with buttons, we are unable to view this list.

A possible solution would be to have a website to display this list of people who upvoted/downvoted the suggestion.

**Comment by Skelmis** [comment]
This is currently blocked by #7, otherwise it's something I'd like to implement

**Comment by Skelmis** [comment]
This can be done in discord utilizing a form of paginated embed so I'd consider it no longer blocked with this issue now being two parts.

1. An in discord command to view users
2. A web UI to view users (better UX)
