### ISSUE TITLE
feat: Error tracking

### ISSUE THREAD

**Issue by Skelmis** [suggestionsbot/suggestions-bot-v3#27]
Given the real-time nature of errors, it'd be nice to have some form of error persistence so that when we are looking to help users we simply search by error ID rather then needing to manually parse logs which are sometimes days worth to maybe find the error.

This would either be done via Garven, or a third party service such as sentry.

My preference is trending towards something in house as the primary use case requires being able to uniquely identify errors, rather then simply tracking if an error has occurred within the service.

**Comment by acollierr17** [comment]
I agree with you on error persistence. Something I wanted to do for a long time was to at least persist error logs to s3 (which we could still do). 

I also think exploring doing something in-house would be a good option. I like Sentry, but with it being paid to scale and having a lot of features, one could argue it being overkill, including us. 

For the in-house option, how would that look? I saw you mentioned Garven, but you're more familiar with the service then me.

**Comment by Skelmis** [comment]
Yea, as much as I'd like to not reinvent the wheel Sentry and other products have a lot of overhead and associated costs.

Option 1:

Essentially I'm thinking an API which would have something like

POST /errors
```json
{"traceback": "traceback", "error": "error name", "user_id": 1, "guild_id": 1, "command_name": "", "cluster_id": ...}
```
Which would return on 201
```json
{"id": ""}
```

With GET /errors/{id}
```json
{"traceback": "traceback", "error": "error name", "user_id": 1, "guild_id": 1, "command_name": "", "cluster_id": 1, "created_at": "" "id": ""}
```

And ideally we could display this data via some form of slash command like ``/error view <id>`` which shows the traceback in discord, as well as having a link to a web ui where we could get more data on it.

---

Option 2:

We don't make an API, we just create another collection in Mongo and have the bot insert the data itself with no reliance on outside services.

This is likely the better option, and then if we did want to make anything web facing it can just have read access to the database.

Typing this out, I'd like to do option 2 + its way simpler

**Comment by acollierr17** [comment]
If you believe option two would be more straightforward and you're leaning more towards that overall, I say let's do it. From there, we can build an API on top of that database collection and implement that new API in various services, including the bot.

Either way, we'd have a lot of options regarding integration. But with option two, we'd be able to start collecting error information a lot sooner.
