### ISSUE TITLE
The year should be 2023

### ISSUE THREAD

**Issue by acollierr17** [suggestionsbot/suggestions-bot-v3#40]
https://github.com/suggestionsbot/suggestions-bot/blob/0b1467f83cae780f07fc67b75fca998c2c942180/suggestions/main.py#L149
It's self-explanatory. The string could be dynamic to prevent manual updates in the future.

**Comment by alaninnovates** [comment]
Code snippet to get current year:
```py
from datetime import datetime
print(datetime.now().year)
```
