### ISSUE TITLE
Incorrect localization wording for description of /clear command "suggestion_id" option

### ISSUE THREAD

**Issue by acollierr17** [suggestionsbot/suggestions-bot-v3#73]
https://github.com/suggestionsbot/suggestions-bot/blob/0195bd125f060b50dd8cf7bbcca82edb420f69f9/suggestions/locales/en_US.json#L25
The string in reference.

All the localizations for the `suggestion_id` option use the word `reject` instead of `clear.`

Only the strings need to be updated in this case.

Here is a preview of the API response and what each localization has returned:
```
{
   "options":{
      "type":3,
      "name":"suggestion_id",
      "name_localizations":{
         "en-GB":"suggestion_id",
         "pt-BR":"id_da_sugestão",
         "fr":"suggestion_id",
         "en-US":"suggestion_id"
      },
      "description":"The sID you wish to clear",
      "description_localizations":{
         "en-GB":"The sID you wish to reject",
         "pt-BR":"O sID que você deseja remover",
         "fr":"L'ID de la suggestion que vous souhaitez rejeter",
         "en-US":"The sID you wish to reject"
      },
      "required":true,
      "autocomplete":true
   }
}
```

**Comment by Davi-the-Mudkip** [comment]
> All the localizations for the `suggestion_id` option use the word `reject` instead of `clear`.

But pt-BR uses `remover` (meaning `clear`, remove) instead of `rejeitar` (meaning `reject`).

**Comment by acollierr17** [comment]
> > All the localizations for the `suggestion_id` option use the word `reject` instead of `clear`.
> 
> But pt-BR uses `remover` (meaning `clear`, remove) instead of `rejeitar` (meaning `reject`).

Thank you for pointing that out. The `pt_BR` localization should be good in this case.
