### ISSUE TITLE
feat: Attaching images to suggestions

### ISSUE THREAD

**Issue by alaninnovates** [suggestionsbot/suggestions-bot-v3#8]
There should be a way to attach images to suggestions with slash commands.

**Comment by acollierr17** [comment]
There are multiple ways to implement this feature into the bot:

**1) Check if a valid image link is in the suggestion**
If a valid image (the link has the extension of `.jpg` or `.png` for example) is detected in the suggestion's content, we can validate it with regex and set that as the embed's image.

**2) Directly take in images via the command**
We could add an `image` option to the `suggest` command with the type [`11`](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type) to allow the user to upload a file. From there, we can validate the file by checking if it's an image. If so, we can set the URL to the embed's `image` field.

Both options could be used interchangeably depending on how the user wants to attach the image.

Thoughts?

**Comment by Skelmis** [comment]
Going with number 2 as:
a) This does not require convoluted regex and checks
b) As it is supported by discord this makes the feature explicit for any end users
